
import React from 'react';
import { MedicalReport } from '../types';
import { FileText, Loader2, CheckCircle2, AlertCircle, Download, Printer } from 'lucide-react';

interface ReportPanelProps {
  report: MedicalReport | undefined;
  isAnalyzing: boolean;
  onAnalyze: () => void;
}

const ReportPanel: React.FC<ReportPanelProps> = ({ report, isAnalyzing, onAnalyze }) => {
  return (
    <div className="flex flex-col h-full bg-slate-900 border-l border-slate-700 w-96 overflow-hidden">
      <div className="p-4 border-b border-slate-700 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-blue-400" />
          <h2 className="font-semibold text-slate-100">Radiological Report</h2>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {!report && !isAnalyzing && (
          <div className="h-full flex flex-col items-center justify-center text-center p-6 space-y-4">
            <div className="w-16 h-16 bg-slate-800 rounded-full flex items-center justify-center">
              <FileText className="w-8 h-8 text-slate-500" />
            </div>
            <div>
              <p className="text-slate-300 font-medium">No Report Generated</p>
              <p className="text-sm text-slate-500 mt-1">Run AI analysis to generate a preliminary medical findings report.</p>
            </div>
            <button
              onClick={onAnalyze}
              className="w-full py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-md transition-colors font-medium text-sm flex items-center justify-center gap-2"
            >
              Start Analysis
            </button>
          </div>
        )}

        {isAnalyzing && (
          <div className="h-full flex flex-col items-center justify-center p-6 space-y-4">
            <Loader2 className="w-10 h-10 text-blue-500 animate-spin" />
            <div className="text-center">
              <p className="text-slate-300 font-medium italic">Processing Pixels...</p>
              <p className="text-xs text-slate-500 mt-1">Applying medical-grade vision heuristics</p>
            </div>
          </div>
        )}

        {report && (
          <div className="animate-in fade-in duration-500 space-y-6 pb-20">
            <div className="bg-blue-900/20 border border-blue-500/30 rounded-md p-3 flex items-start gap-3">
              <CheckCircle2 className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold text-blue-400 uppercase tracking-wider">AI Verified</p>
                <p className="text-[11px] text-blue-200/70 mt-0.5">Report generated by NeuroVision AI Core. Requires clinical validation.</p>
              </div>
            </div>

            <section className="space-y-2">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Findings</h3>
              <p className="text-sm text-slate-300 leading-relaxed font-mono whitespace-pre-line bg-slate-800/50 p-3 rounded border border-slate-700/50">
                {report.findings}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Impression</h3>
              <p className="text-sm text-blue-100 font-semibold leading-relaxed p-3 bg-blue-500/10 rounded border border-blue-500/20">
                {report.impression}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Recommendations</h3>
              <ul className="space-y-2">
                {report.recommendations.map((rec, i) => (
                  <li key={i} className="flex gap-2 text-sm text-slate-400">
                    <span className="text-blue-500 font-bold">•</span>
                    {rec}
                  </li>
                ))}
              </ul>
            </section>

            <div className="pt-6 border-t border-slate-700 flex gap-2">
              <button className="flex-1 py-2 px-3 bg-slate-800 hover:bg-slate-700 rounded text-xs font-medium flex items-center justify-center gap-2 transition-colors">
                <Printer className="w-3.5 h-3.5" />
                Print Report
              </button>
              <button className="flex-1 py-2 px-3 bg-slate-800 hover:bg-slate-700 rounded text-xs font-medium flex items-center justify-center gap-2 transition-colors">
                <Download className="w-3.5 h-3.5" />
                Export PDF
              </button>
            </div>
          </div>
        )}
      </div>

      <div className="p-4 bg-slate-800 border-t border-slate-700 text-[10px] text-slate-500 flex items-center gap-2">
        <AlertCircle className="w-3 h-3 text-amber-500" />
        <span>For clinical simulation only. Accuracy depends on scan quality.</span>
      </div>
    </div>
  );
};

export default ReportPanel;
